// Code generated by protoc-gen-go. DO NOT EDIT.
// source: godis.proto

/*
Package godis_proto is a generated protocol buffer package.

It is generated from these files:
	godis.proto

It has these top-level messages:
	Error
	Response
	Request
	Value
	RepeatedString
	MapString
*/
package godis_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operation int32

const (
	Operation_Remove Operation = 0
	Operation_Get    Operation = 1
	Operation_Set    Operation = 2
	Operation_Keys   Operation = 3
)

var Operation_name = map[int32]string{
	0: "Remove",
	1: "Get",
	2: "Set",
	3: "Keys",
}
var Operation_value = map[string]int32{
	"Remove": 0,
	"Get":    1,
	"Set":    2,
	"Keys":   3,
}

func (x Operation) String() string {
	return proto.EnumName(Operation_name, int32(x))
}
func (Operation) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Error struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	Error *Error `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	Value *Value `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetValue() *Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Request struct {
	Key       string    `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Operation Operation `protobuf:"varint,2,opt,name=operation,enum=godis_proto.Operation" json:"operation,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Request) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Request) GetOperation() Operation {
	if m != nil {
		return m.Operation
	}
	return Operation_Remove
}

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_StringVal
	//	*Value_StringSlice
	//	*Value_StringMap
	Value isValue_Value `protobuf_oneof:"value"`
}

func (m *Value) Reset()                    { *m = Value{} }
func (m *Value) String() string            { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()               {}
func (*Value) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isValue_Value interface {
	isValue_Value()
}

type Value_StringVal struct {
	StringVal string `protobuf:"bytes,1,opt,name=string_val,json=stringVal,oneof"`
}
type Value_StringSlice struct {
	StringSlice *RepeatedString `protobuf:"bytes,2,opt,name=string_slice,json=stringSlice,oneof"`
}
type Value_StringMap struct {
	StringMap *MapString `protobuf:"bytes,3,opt,name=string_map,json=stringMap,oneof"`
}

func (*Value_StringVal) isValue_Value()   {}
func (*Value_StringSlice) isValue_Value() {}
func (*Value_StringMap) isValue_Value()   {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetStringVal() string {
	if x, ok := m.GetValue().(*Value_StringVal); ok {
		return x.StringVal
	}
	return ""
}

func (m *Value) GetStringSlice() *RepeatedString {
	if x, ok := m.GetValue().(*Value_StringSlice); ok {
		return x.StringSlice
	}
	return nil
}

func (m *Value) GetStringMap() *MapString {
	if x, ok := m.GetValue().(*Value_StringMap); ok {
		return x.StringMap
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_StringVal)(nil),
		(*Value_StringSlice)(nil),
		(*Value_StringMap)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_StringVal:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.StringVal)
	case *Value_StringSlice:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StringSlice); err != nil {
			return err
		}
	case *Value_StringMap:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.StringMap); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 1: // value.string_val
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Value_StringVal{x}
		return true, err
	case 2: // value.string_slice
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RepeatedString)
		err := b.DecodeMessage(msg)
		m.Value = &Value_StringSlice{msg}
		return true, err
	case 3: // value.string_map
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MapString)
		err := b.DecodeMessage(msg)
		m.Value = &Value_StringMap{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_StringVal:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.StringVal)))
		n += len(x.StringVal)
	case *Value_StringSlice:
		s := proto.Size(x.StringSlice)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Value_StringMap:
		s := proto.Size(x.StringMap)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RepeatedString struct {
	StringArrayVal []string `protobuf:"bytes,2,rep,name=string_array_val,json=stringArrayVal" json:"string_array_val,omitempty"`
}

func (m *RepeatedString) Reset()                    { *m = RepeatedString{} }
func (m *RepeatedString) String() string            { return proto.CompactTextString(m) }
func (*RepeatedString) ProtoMessage()               {}
func (*RepeatedString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RepeatedString) GetStringArrayVal() []string {
	if m != nil {
		return m.StringArrayVal
	}
	return nil
}

type MapString struct {
	StringMap map[string]string `protobuf:"bytes,1,rep,name=string_map,json=stringMap" json:"string_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MapString) Reset()                    { *m = MapString{} }
func (m *MapString) String() string            { return proto.CompactTextString(m) }
func (*MapString) ProtoMessage()               {}
func (*MapString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MapString) GetStringMap() map[string]string {
	if m != nil {
		return m.StringMap
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "godis_proto.Error")
	proto.RegisterType((*Response)(nil), "godis_proto.Response")
	proto.RegisterType((*Request)(nil), "godis_proto.Request")
	proto.RegisterType((*Value)(nil), "godis_proto.Value")
	proto.RegisterType((*RepeatedString)(nil), "godis_proto.RepeatedString")
	proto.RegisterType((*MapString)(nil), "godis_proto.MapString")
	proto.RegisterEnum("godis_proto.Operation", Operation_name, Operation_value)
}

func init() { proto.RegisterFile("godis.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x6a, 0xdb, 0x40,
	0x10, 0xc6, 0x2d, 0xa9, 0xb6, 0xac, 0x51, 0x11, 0x62, 0x29, 0x45, 0xb4, 0x87, 0xba, 0x82, 0x82,
	0xe8, 0x41, 0x07, 0xbb, 0xd0, 0x62, 0x7a, 0x48, 0x42, 0x4c, 0x0c, 0xc1, 0x84, 0xac, 0xc0, 0xc7,
	0x98, 0x4d, 0x3c, 0x18, 0x11, 0x59, 0xab, 0xec, 0xae, 0x0d, 0x7a, 0x8a, 0xbc, 0x48, 0x1e, 0x32,
	0x68, 0xf5, 0x27, 0x16, 0xf8, 0xb6, 0x33, 0xf3, 0xcd, 0xf7, 0xfd, 0xd8, 0x01, 0x77, 0xc7, 0xb7,
	0xa9, 0x8c, 0x0b, 0xc1, 0x15, 0x27, 0x75, 0xb1, 0xd1, 0x45, 0xf8, 0x13, 0x86, 0x0b, 0x21, 0xb8,
	0x20, 0x01, 0xd8, 0x7b, 0x94, 0x92, 0xed, 0x30, 0x30, 0x26, 0x46, 0xe4, 0xd0, 0xb6, 0x0c, 0x1f,
	0x60, 0x4c, 0x51, 0x16, 0x3c, 0x97, 0x48, 0x22, 0x18, 0x62, 0x25, 0xd7, 0x1a, 0x77, 0x4a, 0xe2,
	0x13, 0xaf, 0x58, 0x1b, 0xd1, 0x5a, 0x50, 0x29, 0x8f, 0x2c, 0x3b, 0x60, 0x60, 0x9e, 0x51, 0xae,
	0xab, 0x09, 0xad, 0x05, 0xe1, 0x3d, 0xd8, 0x14, 0x5f, 0x0e, 0x28, 0x15, 0xf1, 0xc1, 0x7a, 0xc6,
	0xb2, 0x01, 0xa8, 0x9e, 0xe4, 0x0f, 0x38, 0xbc, 0x40, 0xc1, 0x54, 0xca, 0x73, 0x6d, 0xe5, 0x4d,
	0xbf, 0xf6, 0xac, 0xee, 0xda, 0x29, 0xfd, 0x10, 0x86, 0x6f, 0x06, 0x0c, 0x75, 0x06, 0xf9, 0x01,
	0x20, 0x95, 0x48, 0xf3, 0xdd, 0xe6, 0xc8, 0xb2, 0xda, 0x78, 0x39, 0xa0, 0x4e, 0xdd, 0x5b, 0xb3,
	0x8c, 0x5c, 0xc0, 0xe7, 0x46, 0x20, 0xb3, 0xf4, 0xa9, 0xc5, 0xfd, 0xde, 0xcb, 0xa0, 0x58, 0x20,
	0x53, 0xb8, 0x4d, 0xb4, 0x70, 0x39, 0xa0, 0x6e, 0xbd, 0x92, 0x54, 0x1b, 0xe4, 0x6f, 0x17, 0xb1,
	0x67, 0x45, 0x60, 0xe9, 0xfd, 0x3e, 0xe3, 0x8a, 0x15, 0xdd, 0x6a, 0x13, 0xbd, 0x62, 0xc5, 0x95,
	0xdd, 0x7c, 0x51, 0x38, 0x07, 0xaf, 0x1f, 0x41, 0x22, 0xf0, 0x1b, 0x4f, 0x26, 0x04, 0x2b, 0x35,
	0xbc, 0x39, 0xb1, 0x22, 0x87, 0x7a, 0x75, 0xff, 0xb2, 0x6a, 0xaf, 0x59, 0x16, 0xbe, 0x1a, 0xe0,
	0x74, 0xfe, 0xe4, 0xba, 0xc7, 0x62, 0x4c, 0xac, 0xc8, 0x9d, 0xfe, 0x3a, 0xcf, 0x12, 0x27, 0x2d,
	0xc8, 0x22, 0x57, 0xa2, 0x3c, 0x01, 0xfb, 0xf6, 0x1f, 0xbc, 0xfe, 0xf0, 0xcc, 0x61, 0xbe, 0x9c,
	0xde, 0xd7, 0x69, 0x6e, 0x39, 0x37, 0xff, 0x19, 0xbf, 0x67, 0xe0, 0x74, 0x47, 0x21, 0x00, 0x23,
	0x8a, 0x7b, 0x7e, 0x44, 0x7f, 0x40, 0x6c, 0xb0, 0x6e, 0x50, 0xf9, 0x46, 0xf5, 0x48, 0x50, 0xf9,
	0x26, 0x19, 0xc3, 0xa7, 0x5b, 0x2c, 0xa5, 0x6f, 0x3d, 0x8e, 0x34, 0xdd, 0xec, 0x3d, 0x00, 0x00,
	0xff, 0xff, 0x7f, 0x7e, 0x5c, 0x26, 0xaa, 0x02, 0x00, 0x00,
}
